/*Euler Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


var bigMathProblem2 = function() {
var enteredNumber = prompt("Please enter a number no higher than 4,000,000.");
while (isNaN(enteredNumber) || enteredNumber > 4000000){
  enteredNumber = prompt("That entry is invalid, please provide a number no higher than 4,000,000.");
}
var goodNumbers = [];
var finalAnswer = 0;
var x = 1;
while (x <= enteredNumber) {
  if (x % 2 === 0) {
    goodNumbers.push(x);
    x += x;
  } else {
  x += x;
  }
}
for (i = 0; i < goodNumbers.length; i++) {
  finalAnswer += goodNumbers[i];
}
console.log(finalAnswer);
};
bigMathProblem2();
